### ISSUE TITLE
Color codes don't parse in pickaxe lore

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#10] opened 2021-01-31 14:00 UTC
I forgot to check, in the latest v2 beta you gave me in private, the color codes don't parse on the lore. In the config you could set `- 'hello &6orange'` but in-game when you /bm give, the pickaxe will display it as plaintext `hello &6orange` and not actually turn orange (well, 6 is technically gold i guess). 

I thought it was worth to note down, I myself, but i can imagine others might expect it to support color codes. 
It's a minor issue to be fair, but hoping it makes it into a future build. 

![image](https://user-images.githubusercontent.com/28841349/106386348-cee0fd00-63d4-11eb-975c-88ee87662d4a.png)

**Comment by wowkster** [comment] 2021-01-31 23:46
Caused by missing Color Translate call. Fixed in next update

**Closed by wowkster** 2021-01-31 23:46 UTC
Labels: bug

**Comment by mrfloris** [comment] 2021-02-01 07:07
Oooh cool, Thank you for looking into this. Will run it live now and update the pickaxes, we haven't given out a single one yet, so timing +1

+1 Done.
