### ISSUE TITLE
[timeout] error, some remote call freezes during startup times out.

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#4] opened 2021-01-24 04:28 UTC
```
[05:25:35 INFO]: [BedrockMiner] Enabling BedrockMiner v1.5.6

[ 30 seconds freeze during startup here ]

[05:26:05 WARN]: java.net.UnknownHostException: checkip.amazonaws.com
[05:26:05 WARN]: 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
[05:26:05 WARN]: 	at java.base/java.net.Socket.connect(Socket.java:609)
[05:26:05 WARN]: 	at java.base/java.net.Socket.connect(Socket.java:558)
[05:26:05 WARN]: 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[05:26:05 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[05:26:05 WARN]: 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[05:26:05 WARN]: 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[05:26:05 WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
[05:26:05 WARN]: 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
[05:26:05 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
[05:26:05 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[05:26:05 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[05:26:05 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
[05:26:05 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
[05:26:05 WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[05:26:05 WARN]: 	at java.base/java.net.URL.openStream(URL.java:1140)
[05:26:05 WARN]: 	at com.adrianwowk.bedrockminer.BedrockMiner.logHostNames(BedrockMiner.java:148)
[05:26:05 WARN]: 	at com.adrianwowk.bedrockminer.BedrockMiner.onEnable(BedrockMiner.java:79)
[05:26:05 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:26:05 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[05:26:05 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[05:26:05 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[05:26:05 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[05:26:05 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)
[05:26:05 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[05:26:05 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)
[05:26:05 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
[05:26:05 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[05:26:05 INFO]:  [BedrockMiner] Successfully enabled :)
```

Can we a- use the regular spigotmc version checker, b- an option to turn off version checking in config.yml

**Comment by wowkster** [comment] 2021-01-25 13:19
Caused by issue with bStats. Will be fixed in next release

**Closed by wowkster** 2021-01-25 13:19 UTC
Labels: bug

**Comment by mrfloris** [comment] 2021-01-25 14:18
smeths helped me last night and we found it in the code that bstats was probably behind this. Tiding that up will resolve this yeh. Thanks for looking into it.

**Comment by mrfloris** [comment] 2021-01-30 10:22
Update:

The latest build does not include this error anymore. Just fyi.
