### ISSUE TITLE
Exception error: prepareitemcraft

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#11] opened 2021-01-31 16:40 UTC
I noticed this in the console on the live server, not exactly sure what was happening or causing it, thought i'd report it regardless. 

```
[15:58:50 ERROR]: Could not pass event PrepareItemCraftEvent to BedrockMiner v2.0.1-beta-1b
java.lang.NullPointerException: null
        at com.adrianwowk.bedrockminer.events.BedrockMinerEvents.onCraftPrepare(BedrockMinerEvents.java:120) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor303.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-457]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPreCraftEvent(CraftEventFactory.java:1284) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ContainerWorkbench.a(ContainerWorkbench.java:70) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ContainerPlayer.a(ContainerPlayer.java:106) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.InventoryCrafting.setItem(InventoryCrafting.java:135) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.Slot.set(SourceFile:82) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventoryView.setItem(CraftInventoryView.java:53) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.Container.b(Container.java:286) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.Container.a(Container.java:188) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2501) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

```
> ver
[17:40:09 INFO]: This server is running Paper version git-Paper-457 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[17:40:09 INFO]: Checking version, please wait...
[17:40:09 INFO]: Previous version: git-Paper-455 (MC: 1.16.5)
[17:40:09 INFO]: You are running the latest version
>
```

this is from the `BedrockMiner v2.0.1-beta-1b` you gave on discord last night.

**Comment by wowkster** [comment] 2021-01-31 23:45
Caused by a missing null pointer check. Should be fixed in next update.

**Closed by wowkster** 2021-01-31 23:45 UTC
Labels: bug

**Comment by mrfloris** [comment] 2021-02-01 07:06
Excellent, running that live now, will report back if nothings show up. 

1+ Done.
